config/routes.rb
Rails.application.routes.draw do
  post 'dev/api_test'
  get 'dev/summoner'

  root 'pages#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dev_controller.rb
class DevController < ApplicationController
	skip_before_filter :verify_authenticity_token
  require 'lol'
  def api_test
  	@sName = params[:SummonerName]
  end
  def summoner
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

def welcome

end

app/helpers/application_helper.rb
module ApplicationHelper
	#namespacing
	require 'lol'
	include Lol
	
	##
	# Create our summoner objects
	##

	
	
	
	
	
	#
	# We want to call our rito api stuff as rarely as possible, and get the data	# 
	# into our own db / datatyping
	#
	
	
	private def createClientInstance()
	##remember we can't let anybody see this string..
		client = Lol::Client.new "b4b879a7-9939-485f-86e4-b68376d7acc9", {region: "na"}
	end
	
	private def get_api_summoner(summonerName, client)
		returnerSummonerApiObject = client.summoner.by_name(summonerName)
		return returnerSummonerApiObject
	end
	
	
	
	
	
	
	





























##APPLICATION USES

	
	def sayMyName(summonerName)
		client = Lol::Client.new "b4b879a7-9939-485f-86e4-b68376d7acc9", {region: "na"}
		summoner = client.summoner.by_name summonerName
	#ranked_stats = client.stats.ranked(summoner.first.id)
		recent_game = client.game.recent(summoner.first.id)
		return recent_game
	end
	
end

app/helpers/dev_helper.rb
module DevHelper
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dev/api_test.html.erb
<h1>Dev#api-test</h1>
<!-- make this get from the "post method" -->
<%localSummonerName = @sName%>  
<h2>testing api on summoner <%=localSummonerName%><br>

<h1>API REQUEST: <%= summonerObject = sayMyName(localSummonerName)%></h1>

<h1>Stats</h1>
<%# get player information%>
<h2>Player Name: <%=localSummonerName%></h2>
<h2>Player Rank: </h2>

app/views/dev/summoner.html.erb
<%= form_tag dev_api_test_path do %>
  <%= text_field_tag :SummonerName %>
  <%= submit_tag %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CountYourPick</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">CountYourPick</a>
          </div>
          </div>
        </div>
      </nav>

<div class = "container">
<%= yield %>
</div>


</body>
</html>

app/views/pages/welcome.html.erb
</br></br></br></br></br></br></br>
<div id= "container-fluid">
	<center>
<h1>Enter your Summoner Name! </h1>
<%= form_tag dev_api_test_path do %>
  <%= text_field_tag :SummonerName %>
  <%= submit_tag :submit!%>
<% end %>
</center>
</div>
</br></br></br></br></br></br></br>